FROM node:14 As Production

ENV NODE_ENV=production

WORKDIR /user/src/client

COPY package.json .
COPY yarn.lock .


RUN yarn install 
COPY . .
COPY .env ./dist/
RUN yarn build
WORKDIR ./dist

CMD yarn start
