FROM node:14 As Production

ENV NODE_ENV=production

WORKDIR /user/src/client

COPY package.json .
COPY yarn.lock .


RUN yarn install 
COPY . .

ENV GENERATE_SOURCEMAP false

RUN yarn build
WORKDIR ./dist

CMD yarn start
